/*
 * generated by Xtext 2.12.0
 */
package com.utc.utrc.hermes.iml.tests.generator

import com.google.inject.Inject
import com.utc.utrc.hermes.iml.iml.Model
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.eclipse.xtext.testing.validation.ValidationTestHelper
import com.utc.utrc.hermes.iml.tests.ImlInjectorProvider
import com.utc.utrc.hermes.iml.generator.strategies.FunctionEncoder

@RunWith(typeof(XtextRunner))
@InjectWith(typeof(ImlInjectorProvider))

class FunctionEncoderTests {
	
	@Inject extension ParseHelper<Model> 
	@Inject extension ValidationTestHelper
	@Inject FunctionEncoder enc ;
	
	@Test
	def void Test0() {
		val model = '''
			package p;
			type A ;
			type B ;
			type C ;
		'''.parse
		Assert.assertNotNull(model)
		var expr = enc.encode(model);
		System.out.println(expr);
		
	}
	
}
