/*
 * generated by Xtext 2.12.0
 */
package com.utc.utrc.hermes.iml.tests.generator

import com.google.inject.Inject
import com.utc.utrc.hermes.iml.iml.Model
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.eclipse.xtext.testing.validation.ValidationTestHelper
import com.utc.utrc.hermes.iml.tests.ImlInjectorProvider
import com.utc.utrc.hermes.iml.generator.strategies.FunctionEncoder
import com.utc.utrc.hermes.iml.generator.infra.Iml2Symbolic
import com.utc.utrc.hermes.iml.generator.infra.SrlSymbolId
import com.utc.utrc.hermes.iml.generator.infra.SrlNamedTypeSymbol
import com.utc.utrc.hermes.iml.generator.strategies.RecordEncoder

@RunWith(typeof(XtextRunner))
@InjectWith(typeof(ImlInjectorProvider))

class SymbolicTests {
	
	@Inject extension ParseHelper<Model> 
	@Inject extension ValidationTestHelper
	
	@Inject Iml2Symbolic enc ;
	
	
	@Test
	def void Test0() {
		val model = '''
			package p;
			type A ;
			type B ;
			type C {
				v : A ;
			};
		'''.parse
		Assert.assertNotNull(model)
		enc.encode(model);
		val table = enc.symbolTable;
		var renc = new RecordEncoder
		for(SrlSymbolId id : table.symbols.keySet){
			val value = table.symbols.get(id)
			if (value.symbol instanceof SrlNamedTypeSymbol) {
				System.out.println(renc.encode(value.symbol as SrlNamedTypeSymbol))
			}
		}
		
	}
	
}
