/*
 * generated by Xtext 2.12.0
 */
package com.utc.utrc.hermes.iml


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ImlStandaloneSetup extends ImlStandaloneSetupGenerated {

	def static void doSetup() {
		new ImlStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
