/*
 * generated by Xtext 2.12.0
 */
package com.utc.utrc.hermes.iml

import com.google.inject.Injector

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ImlStandaloneSetup extends ImlStandaloneSetupGenerated {
	
	private static Injector injector;
	
	def static synchronized getInjector() {
		if (injector === null) {
			injector = new ImlStandaloneSetup().createInjectorAndDoEMFRegistration();
		}
		return injector;
	}
}
