package com.utc.utrc.hermes.iml.generator.infra;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.naming.QualifiedName;



/**A generic symbol for the SRL. This is an abstract class.
 * An SRL symbol can be linked to one or more IML symbols.
 * There are two categories of symbols: 
 * - Types: They can be named (defined by a ConstrainedType), 
 * or unnamed (generated by a high-order type when defining symbols)
 * - Objects: They correspond to SymbolDeclarations (e.g., fields of a type). 
 * They are used to define variables.
 * 
 * @author pintoa
 *
 */
public  class SrlSymbol extends SrlSymbolId {
	
	public SrlSymbol(IQualifiedNameProvider qnp) {
		super(qnp);
	}

}