/*
 * Copyright (c) 2019 United Technologies Corporation. All rights reserved.
 * See License.txt in the project root directory for license information. */
/*
 * generated by Xtext 2.12.0
 */
package com.utc.utrc.hermes.iml.ide


/**
 * Use this class to register ide components.
 */
class ImlIdeModule extends AbstractImlIdeModule {
}
