/*
 * generated by Xtext 2.12.0
 */
package com.utc.utrc.hermes.iml.ide

import com.google.inject.Guice
import com.utc.utrc.hermes.iml.ImlRuntimeModule
import com.utc.utrc.hermes.iml.ImlStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class ImlIdeSetup extends ImlStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new ImlRuntimeModule, new ImlIdeModule))
	}
	
}
