grammar com.utc.utrc.sexpr.SExpr with org.eclipse.xtext.common.Terminals

generate sExpr "http://www.utc.com/utrc/sexpr/SExpr"

import "http://www.eclipse.org/emf/2002/Ecore" as ecore

Model:
	elements+=Seq*
;

Seq:
	{Seq} '(' elements+=Element* ')'
;

Element:
	Atom | Seq
;

Atom:
	value=SYMBOL
;

terminal SYMBOL:
		ACCEPTABLE_CHAR (ACCEPTABLE_CHAR)*
;

terminal ACCEPTABLE_CHAR: 
	( '\u0021'..'\u0027') | ('\u002A'..'\u007E')
;
