/*
 * generated by Xtext 2.12.0
 */
package com.utc.utrc.sexpr


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SExprRuntimeModule extends AbstractSExprRuntimeModule {
}
