/*
 * generated by Xtext 2.12.0
 */
package com.utc.utrc.sexpr


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SExprStandaloneSetup extends SExprStandaloneSetupGenerated {

	def static void doSetup() {
		new SExprStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
