/*
 * Copyright (c) 2019 United Technologies Corporation. All rights reserved.
 * See License.txt in the project root directory for license information. */
/*
 * generated by Xtext 2.12.0
 */
package com.utc.utrc.hermes.iml.ui.wizard;

import org.eclipse.xtext.ui.wizard.DefaultProjectInfo;

public class ImlProjectInfo extends DefaultProjectInfo {

}
